# Base image de Node.js 18
FROM node:18.18

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración al contenedor
COPY package*.json /app/

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación al contenedor
COPY . /app

# Construir la aplicación
RUN npm run build

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación en producción
CMD ["npm", "run", "start"]




